name: Main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    name: Test job
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16

    - name: Checkout
      uses: actions/checkout@v2

    - name: Download dependencies
      run: go mod download

    - name: Test
      run: export PATH=$PATH:$(go env GOPATH)/bin && make test
